---
key: kgmc_keybert_cossim
model:
  type: IGMC
  num_relations: 8

dataset:
  # keyword_edge_k: 20
  names: 
    - music
    - game
    - office
    - sports
    - book
    - toy
    - office
  keywords: keybert_cossim_matrix.npy

train:
  device: 0
  epochs: 20
  batch_size: 64