---
key: kgmc_lda_cossim
model:
  type: IGMC
  num_relations: 8

dataset:
  keyword_edge_k: 1
  names: 
    - music
    - game
    - office
    - sports
    - book
    - toy
    - office
  keywords: lda_topic_count_matrix.npy

train:
  device: 0
  epochs: 20
  batch_size: 64