---
key: kgmc_egat_keybert_yelp
model:
  type: KGMC
  num_relations: 8

dataset:
  keyword_edge_k: 10
  names: 
    - yelp
  keywords: keybert_cooc_dict.pkl

train:
  device: 0
  epochs: 40
  batch_size: 128
  learning_rates:
    - 1e-3
    - 1e-3
    - 1e-3
    - 1e-3
    - 1e-3
    # - 1e-3
    # - 5e-4
    # - 2e-3
    # - 1e-3
    # - 1e-3
    # - 1e-3
    # - 1e-3