---
key: kgmc_lda_128
model:
  type: KGMC
  num_relations: 8

dataset:
  keyword_edge_k: 20
  names: 
    - music
    - game
    - office
    - sports
    - book
    - toy
    - office
  keywords: lda_topic128_cooc_matrix.npy

train:
  device: 0
  epochs: 20
  batch_size: 64