files:
  # - ./train_configs/igmc_game.yaml
  # - ./train_configs/kgmc_game_keybert.yaml
  # - ./train_configs/igmc_music.yaml
  # - ./train_configs/kgmc_music_keybert.yaml
  # - ./train_configs/igmc_sports.yaml
  # - ./train_configs/kgmc_sports_keybert.yaml
  # - ./train_configs/igmc_toy.yaml
  # - ./train_configs/kgmc_toy_keybert.yaml
  # - ./train_configs/igmc_office.yaml
  # - ./train_configs/kgmc_office_keybert.yaml
  
  - ./train_configs/kgmc_game_tfidf.yaml
  - ./train_configs/kgmc_sports_tfidf.yaml
  - ./train_configs/kgmc_office_tfidf.yaml
  - ./train_configs/kgmc_toy_tfidf.yaml
