---
key: trans_grocery
model:
  type: IGMC
  hop: 1
  in_nfeats: 32
  out_nfeats: 32
  in_efeats: 32
  out_efeats: 32
  latent_dims:
    - 32
    - 32
    - 32
    - 32
  num_heads: 4
  num_relations: 7
  edge_dropout: 0.2
  parameters: kgmc_grocery_keybert_homo_grocery_0.2507.pt

dataset:
  datasets:
    - music
    - games
    - sports
    - movie
    - epinions
  item_cooc_edge_df: item_keybert
  user_cooc_edge_df: user_keybert

train:
  device: 0
  epochs: 20
  batch_size: 128
  learning_rates:
    - 1e-3
    - 2e-3
    - 5e-4
  weight_decay: 0.0
  lr_decay_step: 5
  lr_decay_factor: 0.90
  log_interval: 100
  log_dir: log
  