---
key: baseline_igmc_clothing
model:
  type: IGMC
  hop: 1
  num_relations: 5
  latent_dims:
    - 32
    - 32
    - 32
    - 32
  edge_dropout: 0.5

dataset:
  name: amazon_clothing
  file_name: clothing_core
  efeat: ~

train:
  device: 0
  epochs: 20
  batch_size: 128
  learning_rates:
    - 2e-3
    - 5e-4
    - 1e-4
  weight_decay: 0.0
  lr_decay_step: 5
  lr_decay_factor: 0.90
  log_interval: 100
  log_dir: log
